config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top', to:'users#top', as: :top

  # get 'posts/new', to: 'posts#new', as: new_post

	resources :posts do
		# collection(集合)はidなし、member(個別)はidあり
		member do
			get 'like', to: 'posts#like', as: :like
			post 'comment', to: 'posts#comment', as: :comment
		end
	end


	# resources :users
	get '/', to: 'users#top'

	get '/follower_list/:id', to: 'users#follower_list', as: :follower_list
	get '/follow_list/:id', to:'users#follow_list', as: :follow_list

	get '/:id/follow', to: 'users#follow', as: :follow

	get '/sign_up', to: 'users#sign_up'
	post '/sign_up_process', to: 'users#sign_up_process'

	get '/sign_in', to: 'users#sign_in'
	post '/sign_in_process', to: 'users#sign_in_process'

	get '/sign_out', to: 'users#sign_out', as: :sign_out

	get '/profile/:id', to: 'users#show', as: :profile
	get '/profile/:id/edit', to: 'users#edit', as: :profile_edit
	patch '/profile/:id', to: 'users#update', as: :profile_update
  
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :postlikes
	has_many :post_comments
	has_many :follows
	# follow_user_idをUserのuser.idに紐付けるため、明示する（user_idは自動紐付けのため不要）
	has_many :followers, foreign_key: :follow_user_id, class_name: "Follow"


	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
	validates :password, presence: true, length:{minimum: 6}


	# データの保存前（sign_up_processのUser）に、パスワードを暗号化するメソッド(convert_password)を実行するよう設定
	# before_save でなく before_create にする事で、update時はpassword更新されない
	before_create :convert_password

	# パスワードを暗号化するメソッド
	# ここのselfは、生成されたインスタンスに代わるもの=> sign_up_processのUser.newインスタンス
	def convert_password
		self.password = User.generate_password(self.password)
	end

	# selfつきメソッドを特異メソッド（クラスメソッド）と呼ぶ
	# Userモデルに対して、直接呼び出せる（上記例convert_password）
	# パスワードをmd5に変換するメソッド
	def self.generate_password(password)
		salt = "h!hgamcRAdh38bajhvgai17ysvb"
		Digest::MD5.hexdigest(salt + password)
	end

	# ユーザーがフォローされているかどうかを判定
	def followed_by?(user)
		user.follows.exists?(follow_user_id: self.id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
	before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]

  def top
    if params[:word].present?
      # キーワード検索処理
      # SELECT * FROM posts WHERE caption LIKE '%キーワード%' ORDER BY id DESC;
      @posts = Post.where("caption like ?", "%#{params[:word]}%").order("id desc").page(params[:page])
      flash[:notice] = '検索結果'
    else
      @posts = Post.all.order("id desc").page(params[:page])
    end
    # レコメンド機能
    # pluckを使うと、そのカラムに該当する値を全て配列で取得可能
    @recommends = User.where.not(id: current_user).where.not(id: current_user.follows.pluck(:follow_user_id)).limit(3)
  end

  def show
  	@user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    # アップデート時に初めてプロフィール画像登録が可能
    upload_file = params[:user][:image]
    if upload_file.present?
      # プロフィール更新時にimageが送られていたら、以下の処理へ
      # 画像のファイル名取得（original_filename はファイル名取得のメソッド）
      upload_file_name = upload_file.original_filename
      # public/images のフォルダパスを作成
      # Rails.root を使うと、プロジェクトのルートパスを取得できる
      output_dir = Rails.root.join('public', 'users')
      # フォルダのパスと画像のファイル名を連結して画像のファイルパスを作成
      output_path = output_dir + upload_file_name
      # 画像をアップロード（バイナリで書き込めるモード ('w+b') ）
      # 画像データを読み込み、writeメソッドで実際にファイルにデータを書き込む
      File.open(output_path, 'w+b') do |f|
        f.write(upload_file.read)
      end
      # mergeメソッドで画像データを追加してアップロード
      current_user.update(user_params.merge({image: upload_file_name}))
      flash[:success] = '更新完了'
      redirect_to profile_url
    else
      current_user.update(user_params)
      flash[:success] = '更新完了'
      redirect_to profile_url
    end
  end

# （このユーザーをフォローしてる人）
  def follower_list
  	@user = User.find(params[:id])
    @followers = User.where(id: Follow.where(follow_user_id: @user.id).pluck(:user_id))
  end

# （このユーザーがフォローしてる人）
  def follow_list
  	@user = User.find(params[:id])
    # pluckメソッド は、指定した列を配列として取得する
    @users = User.where(id: Follow.where(user_id: @user.id).pluck(:follow_user_id))
  end

  def sign_up
  	@user = User.new
  	render layout: "application_not_login"
  end

  def sign_up_process
  	user = User.new(user_params)
  	if user.save
  		flash[:success] = "ユーザー登録完了"
  		user_sign_in(user)
  		redirect_to profile_url(user)
  	else
  		flash[:danger] = "ユーザー登録失敗"
  		redirect_to sign_up_url
  	end
  end

  def sign_in
  	@user = User.new
  	render layout: "application_not_login"
  end

  def sign_in_process
  	# パスワードをmd5に変換（passwordは、sign up時に、md5に変換されて保存しているため
  	password_md5 = User.generate_password(user_params[:password])
    # user変数には trueかfalseが
  	user = User.find_by(email: user_params[:email], password: password_md5)
  	if user
      # サインインに成功したら、sessionを作成
  		user_sign_in(user)
  		redirect_to top_path
  	else
  		flash[:danger] = 'サインイン失敗'
  		redirect_to sign_in_url
  	end
  end

  def sign_out
  	user_sign_out
  	flash[:success] = 'サインアウトしました'
  	redirect_to sign_in_path
  end

	# 認証チェック
  def authorize
	redirect_to sign_in_url unless user_signed_in?
  end

  # フォローするか否かの処理
  def follow
    @user = User.find(params[:id])
    if Follow.exists?(user_id: current_user.id, follow_user_id: @user.id)
      Follow.find_by(user_id: current_user.id, follow_user_id: @user.id).destroy
      redirect_back(fallback_location: top_url, notice: "フォローを更新しました。")
    else
      Follow.create(user_id: current_user.id, follow_user_id: @user.id)
      # 直前のページにリダイレクトする場合は、redirect_backメソッド使用
      # もし直前のページがない場合は、fallback_locationオプションで指定されたページへ遷移
      redirect_back(fallback_location: top_url, notice: "フォローを更新しました。")
    end
  end


  private 
  	def user_params
  		params.require(:user).permit(:name, :email, :comment, :password)
  	end
end

app/helpers/users_helper.rb
module UsersHelper

	def user_sign_in(user)
		# セッションに保存
		session[:user_id] = user.id
	end

	def current_user
		if @current_user.nil?
			@current_user = User.find_by(id: session[:user_id])
		else
			@current_user
		end
	end

	def user_sign_out
		session.delete(:user_id)
		@current_user = nil
	end

	def user_signed_in?
		current_user.present?
	end

	def redirect_to_top_if_signed_in
		redirect_to top_url if user_signed_in?
	end

	# プロフィール画像がなかったらダミー画像を指定する
	def image_url(user)
	  if user.image.blank?
	    "https://dummyimage.com/200x200/000/fff"
	  else
	    "/users/#{user.image}"
	  end
	end
end

app/views/users/_profile.html.erb
<div class="profile">
  <div class="image">
    <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
    <!-- image_urlメソッドはヘルパーにてダミー画像かアップロード画像かの分岐をしている -->
  </div>
  <div class="info">
    <div class="name">
      <h1><%= @user.name %></h1>
      <div class="actions">
        <% if @user.id == current_user.id %>
        <div class="edit">
          <%= link_to "プロフィール編集", profile_edit_path %>
        </div>
        <% else %>
        <div class="follow">
          <%= link_to @user.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(@user.id) %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="status">
      <p class="posts_count">投稿数<%= @user.posts.length %>件</p>

      <p class="follower_count"><%= link_to "フォロワー#{@user.followers.length}人", follower_list_path(@user) %></p>
      <p class="follow_count"><%= link_to "#{@user.follows.length}人をフォロー中", follow_list_path(@user) %></p>
    </div>
    <div class="comment">
      <%= @user.comment %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="profile_edit container">
  <!-- routes自己作成の場合、updateのpathをeditと別にしないと送信されない -->
  <%= form_for @user, url: profile_update_path, method: :patch do |f| %>
    <div class="field">
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, placeholder: "名前を入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, placeholder: "メールアドレスを入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :comment, "コメント" %>
      <%= f.text_field :comment, placeholder: "自己紹介など" %>
    </div>
    <div class="field">
      <label>プロフィール画像</label>
      <div class="file_wrap">
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="button_wrap">
      <input type="submit" value="保存する" class="button">
    </div>
  <% end %>
</div>

app/views/users/follow_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- フォローリスト部分 -->
  <h1>このユーザーがフォローした人</h1>
  <% if @users.any? %>
    <ul class="users">
      <% @users.each do |user| %>
      <li>
        <div style="background: url('<%= image_url(user) %>'); background-position: 50%; background-size: cover;" class="image"></div>
        <%= link_to profile_path(user) do %>
          <span class="name"><%= user.name %></span>
        <% end -%>
        <%= link_to user.followed_by?(current_user)? "フォロー解除" : "フォローする", follow_path(user.id), class: "button" %>
      </li>
      <% end -%>
    </ul>
    <% else %>
      <p class="empty">0人</p>
    <% end -%>
</div>

app/views/users/follower_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render 'users/profile' %>
  <!-- フォロワーリスト部分 -->
  <h1>フォロワー（このユーザーをフォローしてる人）</h1>
  <% if @followers.any? %>
    <ul class="users">
      <% @followers.each do |follower| %>
      <li>
        <div style="background: url('<%= image_url(follower) %>'); background-position: 50%; background-size: cover;" class="image"></div>
        <%= link_to profile_path(follower) do %>
          <span class="name"><%= follower.name %></span>
        <% end -%>
        <%= link_to follower.followed_by?(current_user)? "フォロー解除" : "フォローする", follow_path(follower.id), class: "button" %>
      </li>
      <% end -%>
    </ul>
    <% else %>
      <p class="empty">0人</p>
    <% end -%>
</div>

app/views/users/show.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- 投稿画像部分 -->
  <div class="posts">
    <ul>
      <% @posts.each do |post| %>
        <% post.post_images.each do |post_image| %>
        <li>
          <div style="background: url('<%= "/images/#{post_image.name}" %>'); background-repeat: no-repeat; background-position: 50%;"></div>
        </li>
        <% end -%>
      <% end -%>
    </ul>
  </div>
</div>

app/views/users/sign_in.html.erb
<div class="sign_in">
  <div class="contents">
    <div class="sign_in_form">
      <h1>Photo</h1>
      <%= form_for @user, url: sign_in_process_path do |f| %>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>サインインする</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to "新規登録する", sign_up_path %></p>
    </div>
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="sign_up">
  <div class="contents">
    <div class="sign_up_form">
      <h1>Photo</h1>
      <p>友達のphotoをチェックしよう</p>
      <%= form_for @user, url: sign_up_process_path do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "ユーザーネーム" %>
        </div>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>登録する</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <!-- <p>アカウントをお持ちですか？ <a href="users/sign_in">サインインする</a></p> -->
      <p>アカウントをお持ちですか？ <%= link_to "サインインする！", sign_in_path %></p>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="top container">
  <% if @posts.any? %>
    <ul class="posts">
      <div><%= page_entries_info @posts %></div>
      <% @posts.each do |post| %>
      <li>
        <!-- 投稿者のアイコン -->
        <div class="user">
          <div style="background: url('<%= image_url(post.user) %>'); background-position: center; background-size: cover" class="image"></div>
          <p><%= link_to post.user.name, profile_path(post.user) %></p>
        </div>
        <!-- 投稿画像 -->
        <div class="image_wrap">
          <% post.post_images.each do |post_image| %>
            <%= image_tag "/images/#{post_image.name}" %>
          <% end -%>
        </div>
        <!-- テキスト部分 -->
        <div class="info">
          <div class="action">
            <%= link_to like_post_path(post) do %>
              <i class="fa <%= post.like_from?(current_user)? "fa-heart active" : "fa-heart-o" %>"></i><!-- いいねのハート -->
            <% end -%>
            <label for="post-comment-">
              <i class="fa fa-comment-o"></i>
            </label>
            <!-- 画像削除 -->
            <% if post.user.id == current_user.id %>
              <%= link_to post_path(post), method: :delete do %>
                <i class="fa fa-close"></i>
              <% end -%>
            <% end -%>
          </div>
          <div class="like">
            <p>いいね <%= post.postlikes.count %>件</p>
          </div>
          <!-- コメント部分 -->
          <div class="comment">
            <ul>
              <!-- 投稿者のキャプション -->
              <% if post.caption.present? %>
              <li>
                <span class="user_name"><%= post.user.name %></span>
                <span class="caption"><%= post.caption %></span>
              </li>
              <% end -%>
              <!-- 画像へのコメント -->
              <% post.post_comments.each do |post_comment| %>
              <li>
                <span class="user_name"><%= post_comment.user.name %></span>
                <span class="caption"><%= post_comment.comment %></span>
              </li>
              <% end %>
            </ul>
            <!-- コメント入力部分 -->
            <div class="text_wrap">
              <!-- post.post_comments.new と指定して、PostCommentモデルクラスのインスタンスを生成 -->
              <%= form_for post.post_comments.new, url: comment_post_path(post) do |f| %>
                <div class="field">
                  <!-- idにpost-comment-投稿IDと指定することで、Railsのサーバー側で投稿IDの値をパラメータとして受け取ることができる　もちろん、post.id だけでもOK -->
                  <%= f.text_field :comment, id: "post-comment-#{post.id}", placeholder: "コメント入力" %>
                  <%= f.submit "送信" %>
                </div>
              <% end -%>
            </div>
          </div>
        </div>
      </li>
      <% end -%>
      <div><%= paginate @posts %></div>
    </ul>
  <% else %>
    <p class="empty">投稿がありません。</p>
  <% end -%>
  <!-- おすすめユーザー（レコメンド）-->
  <% if @recommends.any? %>
    <div class="recommend">
      <h2>おすすめユーザー</h2>
      <ul>
        <% @recommends.each do |user| %>
        <li>
          <%= link_to profile_path(user) do %>
            <img src="<%= image_url(user) %>">
            <p><%= user.name %></p>
          <% end -%>
          <%= link_to "フォローする", follow_path(user), class: "button" %>
        </li>
        <% end -%>
      </ul>
    </div>      
  <% end -%>
</div>