config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top', to:'users#top', as: :top

  # get 'posts/new', to: 'posts#new', as: new_post

	resources :posts do
		# collection(集合)はidなし、member(個別)はidあり
		member do
			get 'like', to: 'posts#like', as: :like
			post 'comment', to: 'posts#comment', as: :comment
		end
	end


	# resources :users
	get '/', to: 'users#top'

	get '/follower_list/:id', to: 'users#follower_list', as: :follower_list
	get '/follow_list/:id', to:'users#follow_list', as: :follow_list

	get '/:id/follow', to: 'users#follow', as: :follow

	get '/sign_up', to: 'users#sign_up'
	post '/sign_up_process', to: 'users#sign_up_process'

	get '/sign_in', to: 'users#sign_in'
	post '/sign_in_process', to: 'users#sign_in_process'

	get '/sign_out', to: 'users#sign_out', as: :sign_out

	get '/profile/:id', to: 'users#show', as: :profile
	get '/profile/:id/edit', to: 'users#edit', as: :profile_edit
	patch '/profile/:id', to: 'users#update', as: :profile_update
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>
  <body class="logined">
    <header class="global_header">
      <!-- ロゴ -->
      <div class="icon">
        <%= link_to top_path do %>
          <i class="fa fa-camera"></i>
        <% end %>
      </div>
      <%= link_to top_path do %>
        <h1 class="logo">Photo</h1>
      <% end %>
      <!-- 検索フォーム -->
      <form class="search">
        <!-- name="word"となっているため、nameという名前でキーワードの値が送られる -->
        <input type="text" placeholder="検索ワードを入力" name="word" value="">
      </form>
      <!-- メニュー -->
      <ul class="menu">
        <li>
          <!-- サインアウト -->
          <%= link_to sign_out_path do %>
            <i class="fa fa-sign-out"></i>
          <% end -%>
        </li>
        <li>
          <!-- プロフィールページ -->
          <!-- link_to でアイコンとか画像挟むときは、doを使う -->
          <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user-o"></i>
          <% end -%>
        </li>
        <li>
          <!-- 投稿 -->
          <%= link_to new_post_path do %>
            <i class="fa fa-upload"></i>
          <% end -%>
        </li>
      </ul>
    </header>
    <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").slideUp();
        }, 3000);
    </script>


  </body>
</html>

app/views/layouts/application_not_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>


    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>

    
  </body>
</html>